services:
  mysql:
      image: mysql:8.0
      container_name: montink_db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: montink
        MYSQL_USER: userprojeto
        MYSQL_PASSWORD: userpass
      ports:
        - "8037:3306"
      volumes:
        - ./docker/db/data:/var/lib/mysql
      
  php-fpm:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      container_name: montink_app
      extra_hosts: 
            - "host.docker.internal:host-gateway"
      volumes:
        - .:/application
      working_dir: /application
  webserver:
      image: 'nginx:alpine'
      volumes:
          - '.:/application'
          - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
          - '8004:80'
      depends_on: 
        - php-fpm
    
      

